### ISSUE TITLE
Need a reload button

### ISSUE THREAD

**Issue by miguelamda** [Meowcolm024/has-go#2]
Hi,

Thanks a lot for this extension.

I miss a reload button, instead of load GHCi, so that it reloads the file ( :r command) to check errors without having to create a new terminal with ghci.

Best,
Miguel

**Comment by Meowcolm024** [comment]
Sorry for the late reply (as I've disabled the notifications previously)

Actually I'm not that familiar with JavaScript, but I will try my best :)

**Comment by Meowcolm024** [comment]
Hi, I've done the job, see f7b82f0

> To reload, set `Reuse Terminal` in config to `true`

However I used `:l` instead of `:r` as `:l` reloads the file while `:r` reloads the module :)
Thanks for your advice

**Comment by miguelamda** [comment]
Hi,

Cool, thanks a lot! Indeed, it's much better to use `:l` instead of `:r`. FYI, I will recommend your plugin to my students in the Haskell course I'm giving. It's just easy and working fine.

I am very grateful. Congratulations for the plugin.

Best regards

**Comment by Meowcolm024** [comment]
Thank you so much! 😊 
PS: if you find any bugs, feel free to fire issues (or pull requests if possible) as the Fall semester is about to begin and I would have tons of schoolwork to do, so there might be not much time for me to spend on this project :(
