### ISSUE TITLE
Problem when reusing the terminal

### ISSUE THREAD

**Issue by miguelamda** [Meowcolm024/has-go#4]
Hi,

The terminal reusing is failing since a couple of days. I can load the file for the fist time without problem, but when loading again (reusing the terminal), I get the following error:

> *Main> :l "c:\Users\Miguel\practica.hs"
> Couldn't read "\"c:\\Users\\Miguel\\practica.hs\"" as String

Best,
Miguel

**Comment by Meowcolm024** [comment]
Are you using version 0.4.2? (or does it also fails on 0.4.1?)
It seems find on macOS :(

Also, which version of `ghc` are you using?

**Comment by miguelamda** [comment]
Sorry, I forgot to mention the version:

 

I’m in Windows 10, version 0.4.2 and Haskell 8.6.5. It’s weird, it looks like the :l command is correct (I used it correctly so far), but since some days ago I cannot reuse the terminal because of the error I mention.

 

Some of my students are having the same issue.

 

De: Malcolm Law <notifications@github.com> 
Enviado el: lunes, 23 de noviembre de 2020 11:31
Para: Meowcolm024/has-go <has-go@noreply.github.com>
CC: Miguel Á. Martínez-del-Amor <mdelamor@us.es>; Author <author@noreply.github.com>
Asunto: Re: [Meowcolm024/has-go] Problem when reusing the terminal (#4)

 

Are you using version 0.4.2? (or does it also fails on 0.4.1?)
It seems find on macOS :(

**Comment by Meowcolm024** [comment]
If it's 2 days ago, it may be the problem of 0.4.2 (reverting to 0.4.1 may solve the problem)
Otherwise, maybe you need to go back to 0.4.0 :(
I will look into that later

**Comment by miguelamda** [comment]
Thanks! Yes, reverting to 0.4.0 solves the problem.

 

I found the source of the problem. Since the path in Windows uses backspaces, you need to replace each backspace with a double backspace. In this way, you can use the quotes for paths.

 

https://stackoverflow.com/questions/58952109/how-to-load-a-module-that-contains-whitespace-in-ghci

 

Thank you very much again,

 

Best,

Miguel

 

De: Malcolm Law <notifications@github.com> 
Enviado el: lunes, 23 de noviembre de 2020 11:39
Para: Meowcolm024/has-go <has-go@noreply.github.com>
CC: Miguel Á. Martínez-del-Amor <mdelamor@us.es>; Author <author@noreply.github.com>
Asunto: Re: [Meowcolm024/has-go] Problem when reusing the terminal (#4)

 

If it's 2 days ago, it may be the problem of 0.4.2 (reverting to 0.4.1 may solve the problem)
Otherwise, maybe you need to go back to 0.4.0 :(
I will look into that later

**Comment by Meowcolm024** [comment]
By the way, will the error occurs if the load command is manually typed(with the double quote)?

**Comment by miguelamda** [comment]
Yes, the problem happens by typing manually the load command. As I said, I tried to replace every backslash with a double backslash, and it works

 

PS.: Sorry, I my previous email I said backspace, I meant backslash: \ --> \\

 

De: Malcolm Law <notifications@github.com> 
Enviado el: lunes, 23 de noviembre de 2020 11:47
Para: Meowcolm024/has-go <has-go@noreply.github.com>
CC: Miguel Á. Martínez-del-Amor <mdelamor@us.es>; Author <author@noreply.github.com>
Asunto: Re: [Meowcolm024/has-go] Problem when reusing the terminal (#4)

 

By the way, will the error occurs if the load command is manually typed(with the double quote)?

**Comment by Meowcolm024** [comment]
The intention of version 0.4.1 is solving problems associate with paths with space (i.e. adding double quote). However it seems causing issues on Windows systems :(
I also find that even on Unix path with backslashes also causes Issues.
(And replacing `\` with `\\` will probably fix it)

**Comment by Meowcolm024** [comment]
As the code is a mess @_@, it may take some time.
I will find a time to fix it, if not this week, it would be a month later (after my final exam)

**Comment by miguelamda** [comment]
Ok, no problem. I will ask my students to go back to version 0.4.0 and avoid spaces in folder and file names. 

 

Good luck with your final exam!

 

Thanks a lot again,

 

Best,

Miguel

 

De: Malcolm Law <notifications@github.com> 
Enviado el: lunes, 23 de noviembre de 2020 12:04
Para: Meowcolm024/has-go <has-go@noreply.github.com>
CC: Miguel Á. Martínez-del-Amor <mdelamor@us.es>; Author <author@noreply.github.com>
Asunto: Re: [Meowcolm024/has-go] Problem when reusing the terminal (#4)

 

As the code is a mess @_@, it may take some time.
I will find a time to fix it, if not this week, it would be a month later (after my final exam)

**Comment by Meowcolm024** [comment]
Thank you :D

**Comment by Meowcolm024** [comment]
Just got my last final finished an hour ago :)
The issue is now fixed.
